### ISSUE TITLE
Missing abilities

### ISSUE THREAD

**Issue by Inrego** [amki/ElitismHelper#16]
Hey, I've used this for a while and noticed some abilities missing for being reported. I'll update this issue as I find them again, but just off the top of my head, Shadow Smash from the new reaping modifier.
https://www.wowhead.com/spell=288694/shadow-smash

**Comment by Julmara** [comment]
also adding some abilities from raid woud also be nice like the canon from mekadrill

**Comment by amki** [comment]
Raid abilities have been removed because random raids tend to get emotional when you point out their (many) flaws.

We could add them back and maybe only report if you have a or lead?

Am 19. Februar 2019 19:33:08 MEZ schrieb Julmara <notifications@github.com>:
>also adding some abilities from raid woud also be nice like the canon
>from mekadrill
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/amki/ElitismHelper/issues/16#issuecomment-465254629

-- 
Everything not saved will be lost. - Nintendo Quit Screen Message

**Comment by Julmara** [comment]
yes please or add that as a possible option to trigger on or off
when in the future it has an actual ui

**Comment by amki** [comment]
Since Shadowlands is almost over this seems to be irrelevant now. Sorry that it didn't happen.
