### ISSUE TITLE
Make default option end dungeon only

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [amki/ElitismHelper#34]
Hi, 

would it be possible to set the default to only give the details at the end to reduce spam from people who dunno how to config the addon (like me^^)

Also could you maybe add 2 options :
 - One to show the details at the end
 - One to show the details during each fight
And if they exist maybe add them to the '/eh' help text so they are easy to find  :D

The easiest would be a window for the options, but that's likely much longer I suppose :p

Anyway thanks for the addon :)

**Comment by amki** [comment]
The original idea of ElitismHelper is to provide instant feedback. It happened to me quite a lot that people died to random stuff and then had the audacity to ask "heal?".

The instant feedback ElitismHelper provides mitigates this and also serves to remind people about stuff happening on the spot.

If you want to see what you took how much damage from and when Warcraftlogs or Details might be better suited for that case. The end of dungeon report was a feature request from someone but I personally don't think it's very helpful at all.

It is better to see: "Ah I have to dodge this!" than be at the loot chest and think "wow that went bad, whatever we made it afterall".

If ElitismHelper is too spammy there are 2 options for you and your group, don't get hit (the hard one) or increase the threshold so only really bad hits get reported. I think /eh threshold 60 or something should cull most notifications. (the easy one)

If you have another point I'm open for discussion. Maybe it is beneficial to set the default threshold higher? But when it was higher I got some complaints that the addon wasn't even working because you don't take that much damage from failing in lower keys I presume.

**Comment by redlab** [comment]
Best choice: if ElitismHelper is too spammy there are 2 options for you and your group, don't get hit (the hard one
And as an extra, we use the end of dungeon report to have the one with most failure damage pay 5K to 10K gold to the one with least failure damage!

**Comment by chedz-dev** [comment]
Hi, I just did the pull request #49 to the master branch with a configuration UI so we don't have to learn the commands. Hope it is accepted. All comments are welcome for future improvements of the UI.
